version: '3'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_home:/var/jenkins_home'
volumes:
  jenkins_home:
    driver: local
