version: "3.9"

services:
  web:
    image: homeassistant/raspberrypi3-homeassistant:stable
    restart: always
    environment:
      - TZ="America/New_York"
    ports:
      - "8123:8123"
    volumes:
      - data:/config
      
volumes:
  data:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=[username],password=[password],iocharset=utf8,guest,noperm,file_mode=0777,dir_mode=0777"
      device: "//my-nas/share/path/to/folder"

# Known bug with version 2021.7
# https://www.reddit.com/r/homeassistant/comments/og2oss/ha_docker_failing_to_start_after_updating_to/
# make sure to update libseccomp2 on all nodes that can run homeassistant
