version: '3.1'

services:
  opencanary:
    image: opencanary
    hostname: opencanary
    build:
      context: ./dockerfile
      dockerfile: Dockerfile
    ports:
        - "21:21"
    volumes:
        - "$PWD/.opencanary.conf:/root/.opencanary.conf"
        - "$PWD/:/var/log/opencanary/"
