version: "3.9"

services:
  web:
    image: nodered/node-red
    restart: always
    ports:
      - "1880:1880"
    volumes:
      - data:/data
      
volumes:
  data:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=[username],password=[password],iocharset=utf8,guest,noperm,file_mode=0777,dir_mode=0777"
      device: "//my-samba-ip/share/path/to/folder"
