---

version: "3.8"

services:
  builder:
    build:
      context: ./Dockerfile
      dockerfile: Dockerfile
        args:
          OPENCV_VERSION: 4.4.0
    image: opencv-builder
    volumes:
      - "/home/edgar/.pyenv/versions/3.6.12/envs/webcam-env:/app"
