#!/bin/bash

# Wrapper for docker
# 1. add start|stop|restart|backup
# 2. check if mounting volumes exists; if not, create paths
# 3. backup should tar.gz the entire folder and place backup in /tmp/ or env var defined

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

function start_jellyfin {
  echo "Starting Jellyfin on Docker..."
  docker run -d \
   --name jellyfin \
   --user $(id -u):$(id -g) \
   --net=host \
   --volume $SCRIPT_DIR/config:/config \
   --volume $SCRIPT_DIR/cache:/cache \
   --mount type=bind,source=/mnt/sdb/videos/movies,target=/movies,readonly \
   --mount type=bind,source=/mnt/sdb/videos/tv,target=/shows,readonly \
   --restart=unless-stopped \
   jellyfin/jellyfin
}

function stop_jellyfin {
  echo "Stopping Jellyfin Service..."
  docker stop jellyfin
  docker container rm jellyfin
}

function backup {
  echo "Creating Backup..."
  FILENAME="jellyfin_$(date -I).tar.gz"
  tar czf /tmp/$FILENAME .
}


if [ ! -d "config" ]
then
  echo "config folder missing. creating..."
  mkdir config
  chmod 777 config
fi

if [ ! -d "cache" ]
then
  echo "cache folder missing. creating..."
  mkdir cache
  chmod 777 cache
fi

cmd="$1"

case "$cmd" in
  "start")
    start_jellyfin
    ;;
  "stop")
    stop_jellyfin
    ;;
  "restart")
    echo "Restarting Jellyfin service..."
    stop_jellyfin
    sleep 3  # allow docker to remove container
    start_jellyfin
    ;;
  "backup")
    backup
    ;;
  *)
    echo "Invalid option"
    exit 1
    ;;
esac
