version: '3'
services:

  elasticsearch:
    image: elasticsearch:7.2.0
    ports:
      - 9200:9200
      - 9300:9300
#    restart: always
    container_name: elastic
    hostname: elasticsearch
    networks:
      - logging
    environment:
      ES_JAVA_OPTS: "-Xmx265m -Xms265m"
      discovery.type: "single-node"
#      network.host: "0.0.0.0"
#      bootstrap.seccomp: "false"

  kibana:
    image: kibana:7.2.0
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    container_name: kibana
    hostname: kibana
#    links:
#      - elasticsearch:elasticsearch
    networks:
      - logging

  logstash:
    image: logstash:7.2.0
    ports:
      - 5000:5000
      - 9600:9600
    volumes:
      - "$PWD:/config-dir"
    restart: always
    container_name: logstash
    hostname: logstash
    depends_on:
      - elasticsearch
    networks:
      - logging
    command: logstash -f /config-dir/logstash.conf

networks:
  logging:
    driver: bridge
