version: '3'
services:

  elasticsearch:
    image: elasticsearch:7.8.1
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
    container_name: elastic
    hostname: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx265m -Xms265m"
      discovery.type: "single-node"
#      network.host: "0.0.0.0"
#      bootstrap.seccomp: "false"

  kibana:
    image: kibana:7.8.1
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    container_name: kibana
    hostname: kibana
#    links:
#      - elasticsearch:elasticsearch

  logstash:
    image: logstash:7.8.1
    ports:
      - 514:5000/udp
      - 9600:9600
    volumes:
      - "$PWD/pipeline/:/usr/share/logstash/pipeline/"
    restart: always
    container_name: logstash
    hostname: logstash
    depends_on:
      - elasticsearch

  curator:
    build:
      context: .
      dockerfile: curator.dockerfile
    image: curator
    restart: always
    container_name: curator
    hostname: curator
    volumes:
      - "$PWD:/app/"
    command: "--config /app/curator_conf.yml /app/curator_action.yml"
    depends_on:
      - elasticsearch
    deploy:
      restart_policy:
        delay: 3600s
