version: '3'
services:
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    container_name: elasticsearch
    hostname: elasticsearch
    networks:
      - logging
  kibana:
    image: kibana
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    container_name: kibana
    hostname: kibana
#    links:
#      - elasticsearch:elasticsearch
    networks:
      - logging
  logstash:
    image: logstash
    volumes:
      - "$PWD":/config-dir
    restart: always
    container_name: logstash
    hostname: logstash
    networks:
      - logging
    command: logstash -f /config-dir/logstash.conf
