version: '3.5'

services:
    ngrok:
        # docker run -it -e NGROK_AUTHTOKEN=<token> ngrok/ngrok http 80
        image: ngrok/ngrok
        command: http 80
    drone:
        image: drone/drone:2
        ports:
            - 8000:80
            - 9000:443
        networks:
            - drone
        volumes:
            - ./drone-data:/var/lib/drone/
            - /var/run/docker.sock:/var/run/docker.sock
        env_file:
            - ./drone.env
        restart: always
        environment:
            - DRONE_GITHUB_SKIP_VERIFY=true
            - DRONE_AGENTS_ENABLED=true
            - DRONE_SERVER_HOST=localhost:8000
            - DRONE_SERVER_PROTO=http
            - DRONE_TLS_AUTOCERT=false
            - DRONE_OPEN=false
            - DRONE_HOST=http://localhost:8000
            - DRONE_GITHUB=true

    runner:
        image: drone/agent:1
        # command: agent
        restart: always
        ports:
            - 3000:3000
        depends_on:
            - drone
        networks:
            - drone
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        env_file:
            - ./drone.env
        environment:
            - DRONE_RPC_HOST=drone:8000
            - DRONE_RPC_PROTO=http

networks:
    drone:
        name: drone_network
