#!/bin/bash

docker run -it --rm \
    --mount type=bind,src=$PWD/data,dst=/data \
    -e SYNAPSE_SERVER_NAME=my.matrixhost.com \
    -e SYNAPSE_REPORT_STATS=no \
    matrixdotorg/synapse:latest generate
